In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('UDISE_2023-24_Table_2.1.csv')

In [7]:
df.head(6)

,Sl. No.,India/State/UT,Total Number of - Schools,Total Number of - Enrolments,Total Number of - Teachers,Percentage Share of Schools by Category - Primary,Percentage Share of Schools by Category - Upper Primary,Percentage Share of Schools by Category - Secondary,Percentage Share of Schools by Category - Higher Secondary,Percentage Share of Enrolments by level - Primary,Percentage Share of Enrolments by level - Upper Primary,Percentage Share of Enrolments by level - Secondary,Percentage Share of Enrolments by level - Higher Secondary,Percentage Share of Teachers by School Category - Primary,Percentage Share of Teachers by School Category - Upper Primary,Percentage Share of Teachers by School Category - Secondary,Percentage Share of Teachers by School Category - Higher Secondary
0,1,India,1471891,248045828,9807600,50.0,29.4,9.8,10.8,48.7,25.4,14.9,10.9,24.0,28.6,16.2,31.1
1,2,Andaman and Nicobar Islands,412,72119,5750,50.7,19.2,13.1,17.0,46.1,23.6,15.9,14.4,17.3,16.9,17.5,48.3
2,3,Andhra Pradesh,61373,8741885,338293,61.5,13.5,18.9,6.1,46.1,25.7,16.5,11.6,28.6,14.0,42.7,14.7
3,4,Arunachal Pradesh,3490,323717,24700,48.6,36.8,9.5,5.2,53.7,24.0,13.4,8.9,19.1,42.6,20.6,17.6
4,5,Assam,56630,6922533,342199,66.2,16.7,12.5,4.7,53.4,25.1,14.3,7.2,32.6,20.5,29.1,17.8
5,6,Bihar,94686,21348149,657063,44.0,42.7,2.0,11.2,54.1,26.4,11.7,7.7,23.9,54.7,3.2,18.2

In [8]:
df.tail(5)

,Sl. No.,India/State/UT,Total Number of - Schools,Total Number of - Enrolments,Total Number of - Teachers,Percentage Share of Schools by Category - Primary,Percentage Share of Schools by Category - Upper Primary,Percentage Share of Schools by Category - Secondary,Percentage Share of Schools by Category - Higher Secondary,Percentage Share of Enrolments by level - Primary,Percentage Share of Enrolments by level - Upper Primary,Percentage Share of Enrolments by level - Secondary,Percentage Share of Enrolments by level - Higher Secondary,Percentage Share of Teachers by School Category - Primary,Percentage Share of Teachers by School Category - Upper Primary,Percentage Share of Teachers by School Category - Secondary,Percentage Share of Teachers by School Category - Higher Secondary
32,33,Telangana,42901,7293644,341460,47.9,17.4,27.0,7.7,47.8,25.2,15.3,11.8,14.3,16.0,52.7,16.9
33,34,Tripura,4923,689408,37661,50.2,25.3,13.6,10.8,48.4,25.2,14.6,11.8,20.5,20.0,21.8,37.6
34,35,Uttar Pradesh,255087,41662794,1538479,52.3,34.0,4.7,9.0,49.4,25.4,13.7,11.5,36.6,34.1,5.6,23.7
35,36,Uttarakhand,22551,2372400,130741,57.3,24.4,6.2,12.0,47.7,24.2,15.0,13.1,23.7,25.2,8.8,42.3
36,37,West Bengal,93945,18015525,576557,79.3,9.2,3.5,8.1,47.0,24.5,17.0,11.5,52.2,6.7,6.5,34.6

In [9]:
df.

(37, 17)

In [10]:
df.columns

Index(['Sl. No.', 'India/State/UT', 'Total Number of - Schools',
       'Total Number of - Enrolments', 'Total Number of - Teachers',
       'Percentage Share of Schools by Category - Primary',
       'Percentage Share of Schools by Category - Upper Primary',
       'Percentage Share of Schools by Category - Secondary',
       'Percentage Share of Schools by Category - Higher Secondary',
       'Percentage Share of Enrolments by level -  Primary ',
       'Percentage Share of Enrolments by level -  Upper Primary ',
       'Percentage Share of Enrolments by level - Secondary',
       'Percentage Share of Enrolments by level - Higher Secondary',
       'Percentage Share of Teachers by School Category - Primary',
       'Percentage Share of Teachers by School Category - Upper Primary',
       'Percentage Share of Teachers by School Category - Secondary',
       'Percentage Share of Teachers by School Category - Higher Secondary'],
      dtype='str')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 17 columns):
 #   Column                                                              Non-Null Count  Dtype
---  ------                                                              --------------  -----
 0   Sl. No.                                                             37 non-null     int64
 1   India/State/UT                                                      37 non-null     str
 2   Total Number of - Schools                                           37 non-null     int64
 3   Total Number of - Enrolments                                        37 non-null     int64
 4   Total Number of - Teachers                                          37 non-null     int64
 5   Percentage Share of Schools by Category - Primary                   37 non-null     float64
 6   Percentage Share of Schools by Category - Upper Primary             37 non-null     float64
 7   Percentage Share of Schools by Category - Secondary                 37 non-null     float64
 8   Percentage Share of Schools by Category - Higher Secondary          37 non-null     float64
 9   Percentage Share of Enrolments by level -  Primary                  37 non-null     float64
 10  Percentage Share of Enrolments by level -  Upper Primary            37 non-null     float64
 11  Percentage Share of Enrolments by level - Secondary                 37 non-null     float64
 12  Percentage Share of Enrolments by level - Higher Secondary          37 non-null     float64
 13  Percentage Share of Teachers by School Category - Primary           37 non-null     float64
 14  Percentage Share of Teachers by School Category - Upper Primary     37 non-null     float64
 15  Percentage Share of Teachers by School Category - Secondary         37 non-null     float64
 16  Percentage Share of Teachers by School Category - Higher Secondary  37 non-null     float64
dtypes: float64(12), int64(4), str(1)
memory usage: 5.0 KB

In [12]:
df.sort_values(by=['Percentage Share of Schools by Category - Primary', 'Percentage Share of Schools by Category - Primary'], ascending=False).head(5)

,Sl. No.,India/State/UT,Total Number of - Schools,Total Number of - Enrolments,Total Number of - Teachers,Percentage Share of Schools by Category - Primary,Percentage Share of Schools by Category - Upper Primary,Percentage Share of Schools by Category - Secondary,Percentage Share of Schools by Category - Higher Secondary,Percentage Share of Enrolments by level - Primary,Percentage Share of Enrolments by level - Upper Primary,Percentage Share of Enrolments by level - Secondary,Percentage Share of Enrolments by level - Higher Secondary,Percentage Share of Teachers by School Category - Primary,Percentage Share of Teachers by School Category - Upper Primary,Percentage Share of Teachers by School Category - Secondary,Percentage Share of Teachers by School Category - Higher Secondary
36,37,West Bengal,93945,18015525,576557,79.3,9.2,3.5,8.1,47.0,24.5,17.0,11.5,52.2,6.7,6.5,34.6
4,5,Assam,56630,6922533,342199,66.2,16.7,12.5,4.7,53.4,25.1,14.3,7.2,32.6,20.5,29.1,17.8
23,24,Meghalaya,14601,1052884,55726,62.7,24.2,10.2,2.9,63.9,20.6,10.4,5.1,42.5,26.9,19.9,10.7
2,3,Andhra Pradesh,61373,8741885,338293,61.5,13.5,18.9,6.1,46.1,25.7,16.5,11.6,28.6,14.0,42.7,14.7
13,14,Himachal Pradesh,17826,1426412,101131,60.8,14.0,10.0,15.2,47.9,23.4,15.6,13.1,21.5,10.9,16.9,50.7

In [13]:
df.describe()

,Sl. No.,Total Number of - Schools,Total Number of - Enrolments,Total Number of - Teachers,Percentage Share of Schools by Category - Primary,Percentage Share of Schools by Category - Upper Primary,Percentage Share of Schools by Category - Secondary,Percentage Share of Schools by Category - Higher Secondary,Percentage Share of Enrolments by level - Primary,Percentage Share of Enrolments by level - Upper Primary,Percentage Share of Enrolments by level - Secondary,Percentage Share of Enrolments by level - Higher Secondary,Percentage Share of Teachers by School Category - Primary,Percentage Share of Teachers by School Category - Upper Primary,Percentage Share of Teachers by School Category - Secondary,Percentage Share of Teachers by School Category - Higher Secondary
count,37.000000,3.700000e+01,3.700000e+01,3.700000e+01,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000,37.000000
mean,19.000000,7.956168e+04,1.340788e+07,5.301405e+05,47.435135,26.529730,12.770270,13.259459,49.981081,24.275676,14.700000,11.035135,21.289189,25.681081,20.027027,32.986486
std,10.824355,2.407658e+05,4.057760e+07,1.598759e+06,12.635844,10.954955,7.426935,9.885299,4.459125,1.943994,1.481178,2.427415,9.214053,13.770517,12.912067,16.900151
min,1.000000,3.700000e+01,1.259100e+04,9.110000e+02,6.100000,5.200000,0.000000,2.900000,44.200000,20.500000,10.400000,5.100000,2.000000,4.400000,0.000000,9.400000
25%,10.000000,3.490000e+03,3.237170e+05,2.470000e+04,40.500000,17.400000,7.300000,6.200000,46.200000,23.400000,13.700000,9.100000,16.200000,14.000000,10.700000,18.200000
50%,19.000000,2.351700e+04,5.599742e+06,2.065910e+05,48.600000,25.300000,11.500000,10.100000,48.700000,24.600000,14.900000,11.500000,20.500000,25.200000,18.900000,29.400000
75%,28.000000,6.137300e+04,1.149671e+07,3.940530e+05,53.300000,35.700000,16.500000,16.000000,52.100000,25.700000,15.900000,13.000000,23.900000,36.500000,26.200000,48.700000
max,37.000000,1.471891e+06,2.480458e+08,9.807600e+06,79.300000,50.400000,30.400000,45.200000,63.900000,27.600000,17.300000,15.800000,52.200000,56.100000,53.200000,71.500000

In [15]:
df["India/State/UT"]

0                                        India
1                  Andaman and Nicobar Islands
2                               Andhra Pradesh
3                            Arunachal Pradesh
4                                        Assam
5                                        Bihar
6                                   Chandigarh
7                                 Chhattisgarh
8     Dadra and Nagar Haveli and Daman and Diu
9                                        Delhi
10                                         Goa
11                                     Gujarat
12                                     Haryana
13                            Himachal Pradesh
14                           Jammu and Kashmir
15                                   Jharkhand
16                                   Karnataka
17                                      Kerala
18                                      Ladakh
19                                 Lakshadweep
20                              Madhya Pradesh
21                                 Maharashtra
22                                     Manipur
23                                   Meghalaya
24                                     Mizoram
25                                    Nagaland
26                                      Odisha
27                                  Puducherry
28                                      Punjab
29                                   Rajasthan
30                                      Sikkim
31                                  Tamil Nadu
32                                   Telangana
33                                     Tripura
34                               Uttar Pradesh
35                                 Uttarakhand
36                                 West Bengal
Name: India/State/UT, dtype: str

In [18]:
df[[
    "India/State/UT",
    "Total Number of - Teachers",
    "Percentage Share of Schools by Category - Secondary"
]]

,India/State/UT,Total Number of - Teachers,Percentage Share of Schools by Category - Secondary
0,India,9807600,9.8
1,Andaman and Nicobar Islands,5750,13.1
2,Andhra Pradesh,338293,18.9
3,Arunachal Pradesh,24700,9.5
4,Assam,342199,12.5
5,Bihar,657063,2.0
6,Chandigarh,10237,30.4
7,Chhattisgarh,278798,4.8
8,Dadra and Nagar Haveli and Daman and Diu,4995,8.8
9,Delhi,160479,6.2
10,Goa,14594,28.4
11,Gujarat,394053,8.3
12,Haryana,250909,11.8
13,Himachal Pradesh,101131,10.0
14,Jammu and Kashmir,167046,13.2
15,Jharkhand,206591,7.3
16,Karnataka,433942,21.5
17,Kerala,291096,12.5
18,Ladakh,6432,11.5
19,Lakshadweep,911,0.0
20,Madhya Pradesh,639525,6.7
21,Maharashtra,738114,16.5
22,Manipur,40921,20.8
23,Meghalaya,55726,10.2
24,Mizoram,23013,18.3
25,Nagaland,32602,21.4
26,Odisha,335496,15.3
27,Puducherry,13202,25.2
28,Punjab,273092,14.6
29,Rajasthan,775745,6.8
30,Sikkim,15489,11.5
31,Tamil Nadu,550558,9.7
32,Telangana,341460,27.0
33,Tripura,37661,13.6
34,Uttar Pradesh,1538479,4.7
35,Uttarakhand,130741,6.2
36,West Bengal,576557,3.5

In [20]:
df.sort_values(
    by="Total Number of - Schools",
    ascending=False
)[["India/State/UT", "Percentage Share of Schools by Category - Upper Primary"]].head(10)

    India/State/UT  Percentage Share of Schools by Category - Upper Primary
0            India                                               29.4
34   Uttar Pradesh                                               34.0
20  Madhya Pradesh                                               35.7
21     Maharashtra                                               27.0
29       Rajasthan                                               32.0
5            Bihar                                               42.7
36     West Bengal                                                9.2
16       Karnataka                                               40.0
26          Odisha                                               33.8
2   Andhra Pradesh                                               13.5

In [26]:
df.sort_values(
    by="Total Number of - Teachers",
    ascending=False
)[["India/State/UT", "Total Number of - Enrolments"]].head(10)

    India/State/UT  Total Number of - Enrolments
0            India                     248045828
34   Uttar Pradesh                      41662794
29       Rajasthan                      16786065
21     Maharashtra                      21375970
5            Bihar                      21348149
20  Madhya Pradesh                      15361543
36     West Bengal                      18015525
31      Tamil Nadu                      12993050
16       Karnataka                      11926303
11         Gujarat                      11496709

In [27]:
# Write your code here

In [28]:
df.sort_values(
    by="Percentage Share of Schools by Category - Primary",
    ascending=False
)[["India/State/UT", "Percentage Share of Enrolments by level - Higher Secondary"]].head(10)

,India/State/UT,Percentage Share of Enrolments by level - Higher Secondary
36,West Bengal,11.5
4,Assam,7.2
23,Meghalaya,5.1
2,Andhra Pradesh,11.6
13,Himachal Pradesh,13.1
10,Goa,12.8
31,Tamil Nadu,13.8
7,Chhattisgarh,9.7
35,Uttarakhand,13.1
30,Sikkim,13.0

In [29]:
df[df["India/State/UT"] == "Kerala"]

,Sl. No.,India/State/UT,Total Number of - Schools,Total Number of - Enrolments,Total Number of - Teachers,Percentage Share of Schools by Category - Primary,Percentage Share of Schools by Category - Upper Primary,Percentage Share of Schools by Category - Secondary,Percentage Share of Schools by Category - Higher Secondary,Percentage Share of Enrolments by level - Primary,Percentage Share of Enrolments by level - Upper Primary,Percentage Share of Enrolments by level - Secondary,Percentage Share of Enrolments by level - Higher Secondary,Percentage Share of Teachers by School Category - Primary,Percentage Share of Teachers by School Category - Upper Primary,Percentage Share of Teachers by School Category - Secondary,Percentage Share of Teachers by School Category - Higher Secondary
17,18,Kerala,15864,6281704,291096,40.4,28.1,12.5,19.0,46.3,23.7,15.8,14.2,15.9,20.8,14.6,48.7

In [32]:
df[df["Percentage Share of Teachers by School Category - Secondary"] < 70][[
    "India/State/UT",
    "Percentage Share of Schools by Category - Secondary"
]]

,India/State/UT,Percentage Share of Schools by Category - Secondary
0,India,9.8
1,Andaman and Nicobar Islands,13.1
2,Andhra Pradesh,18.9
3,Arunachal Pradesh,9.5
4,Assam,12.5
5,Bihar,2.0
6,Chandigarh,30.4
7,Chhattisgarh,4.8
8,Dadra and Nagar Haveli and Daman and Diu,8.8
9,Delhi,6.2
10,Goa,28.4
11,Gujarat,8.3
12,Haryana,11.8
13,Himachal Pradesh,10.0
14,Jammu and Kashmir,13.2
15,Jharkhand,7.3
16,Karnataka,21.5
17,Kerala,12.5
18,Ladakh,11.5
19,Lakshadweep,0.0
20,Madhya Pradesh,6.7
21,Maharashtra,16.5
22,Manipur,20.8
23,Meghalaya,10.2
24,Mizoram,18.3
25,Nagaland,21.4
26,Odisha,15.3
27,Puducherry,25.2
28,Punjab,14.6
29,Rajasthan,6.8
30,Sikkim,11.5
31,Tamil Nadu,9.7
32,Telangana,27.0
33,Tripura,13.6
34,Uttar Pradesh,4.7
35,Uttarakhand,6.2
36,West Bengal,3.5

In [36]:
df["Percentage Share of Schools by Category - Primary"].min()

np.float64(6.1)